# src/evalloc/inference/qwen2_vl.py

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Sequence

import torch
from PIL import Image
from qwen_vl_utils import process_vision_info
from transformers import (
    AutoProcessor,
    Qwen2VLForConditionalGeneration,
)


TorchDTypeName = Literal[
    "auto",
    "float16",
    "bfloat16",
    "float32",
]


@dataclass(frozen=True)
class GenerationResult:
    """
    Raw inference result from Qwen2-VL.
    """

    text: str
    input_token_count: int
    generated_token_count: int


class Qwen2VLInferencer:
    """
    Qwen2-VL inference wrapper for selected video frames.

    Selected video frames are provided as an ordered sequence of PIL images.
    They are treated as multiple chronological visual inputs rather than
    passing the complete video file to the model.
    """

    def __init__(
        self,
        model_name: str = "Qwen/Qwen2-VL-7B-Instruct",
        *,
        device_map: str | dict = "auto",
        torch_dtype: TorchDTypeName = "bfloat16",
        attn_implementation: str | None = None,
        min_pixels: int | None = None,
        max_pixels: int | None = None,
        max_new_tokens: int = 16,
        do_sample: bool = False,
    ) -> None:
        self.model_name = model_name
        self.device_map = device_map
        self.torch_dtype = self._resolve_dtype(torch_dtype)
        self.attn_implementation = attn_implementation
        self.min_pixels = min_pixels
        self.max_pixels = max_pixels
        self.max_new_tokens = max_new_tokens
        self.do_sample = do_sample

        self.model: Qwen2VLForConditionalGeneration | None = None
        self.processor = None

    def load(self) -> None:
        """
        Load model and processor.

        Loading is explicit so dataset validation and dry-run checks can be
        performed without allocating GPU memory.
        """
        if self.model is not None and self.processor is not None:
            return

        model_kwargs: dict = {
            "device_map": self.device_map,
            "torch_dtype": self.torch_dtype,
        }

        if self.attn_implementation is not None:
            model_kwargs["attn_implementation"] = self.attn_implementation

        self.model = Qwen2VLForConditionalGeneration.from_pretrained(
            self.model_name,
            **model_kwargs,
        )

        processor_kwargs: dict = {}

        if self.min_pixels is not None:
            processor_kwargs["min_pixels"] = self.min_pixels

        if self.max_pixels is not None:
            processor_kwargs["max_pixels"] = self.max_pixels

        self.processor = AutoProcessor.from_pretrained(
            self.model_name,
            **processor_kwargs,
        )

        self.model.eval()

    @torch.inference_mode()
    def generate(
        self,
        *,
        frames: Sequence[Image.Image],
        prompt: str,
    ) -> GenerationResult:
        """
        Generate an answer from chronologically ordered frames.

        Args:
            frames:
                Ordered PIL images selected from the video.
            prompt:
                Text prompt generated by PromptBuilder.

        Returns:
            GenerationResult containing raw generated text and token counts.
        """
        if not frames:
            raise ValueError("At least one frame is required for inference.")

        if not prompt.strip():
            raise ValueError("prompt must not be empty.")

        self.load()

        assert self.model is not None
        assert self.processor is not None

        messages = [
            {
                "role": "user",
                "content": [
                    *[
                        {
                            "type": "image",
                            "image": frame,
                        }
                        for frame in frames
                    ],
                    {
                        "type": "text",
                        "text": prompt,
                    },
                ],
            }
        ]

        chat_text = self.processor.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )

        image_inputs, video_inputs = process_vision_info(messages)

        inputs = self.processor(
            text=[chat_text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        )

        target_device = self._get_input_device()
        inputs = inputs.to(target_device)

        generated_ids = self.model.generate(
            **inputs,
            max_new_tokens=self.max_new_tokens,
            do_sample=self.do_sample,
        )

        input_length = inputs.input_ids.shape[1]

        trimmed_generated_ids = [
            output_ids[input_length:]
            for output_ids in generated_ids
        ]

        generated_texts = self.processor.batch_decode(
            trimmed_generated_ids,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        )

        generated_text = generated_texts[0].strip()
        generated_token_count = len(trimmed_generated_ids[0])

        return GenerationResult(
            text=generated_text,
            input_token_count=int(input_length),
            generated_token_count=int(generated_token_count),
        )

    def _get_input_device(self) -> torch.device:
        assert self.model is not None

        # device_map="auto" can distribute model modules across devices.
        # hf_device_map gives the first actual execution device.
        hf_device_map = getattr(self.model, "hf_device_map", None)

        if isinstance(hf_device_map, dict):
            for device_value in hf_device_map.values():
                if device_value in {"cpu", "disk"}:
                    continue

                if isinstance(device_value, int):
                    return torch.device(f"cuda:{device_value}")

                return torch.device(str(device_value))

        return self.model.device

    @staticmethod
    def _resolve_dtype(
        dtype_name: TorchDTypeName,
    ) -> torch.dtype | str:
        mapping: dict[str, torch.dtype | str] = {
            "auto": "auto",
            "float16": torch.float16,
            "bfloat16": torch.bfloat16,
            "float32": torch.float32,
        }

        if dtype_name not in mapping:
            raise ValueError(
                f"Unsupported torch dtype: {dtype_name}. "
                f"Available values: {list(mapping)}"
            )

        return mapping[dtype_name]