from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterator

from evalloc.data.base import BaseQADataset, QASample


class VideoMMEDataset(BaseQADataset):
    """
    Dataset loader for processed Video-MME annotations.

    This class expects a JSONL file generated by scripts/prepare_videomme.py.
    Each line should follow the common QASample-compatible format:

    {
        "sample_id": "...",
        "video_path": "...",
        "question": "...",
        "task_type": "multi_choice",
        "options": ["...", "...", "...", "..."],
        "answer": "A",
        "duration": 123.4,
        "metadata": {...}
    }
    """

    def __init__(
        self,
        annotation_path: str | Path,
        *,
        video_root: str | Path | None = None,
        require_video_exists: bool = True,
        require_answer: bool = True,
        max_samples: int | None = None,
    ) -> None:
        self.annotation_path = Path(annotation_path)
        self.video_root = Path(video_root) if video_root is not None else None
        self.require_video_exists = require_video_exists
        self.require_answer = require_answer

        if not self.annotation_path.exists():
            raise FileNotFoundError(
                f"Annotation file does not exist: {self.annotation_path}"
            )

        self.samples = self._load_samples()

        if max_samples is not None:
            self.samples = self.samples[:max_samples]

        if len(self.samples) == 0:
            raise RuntimeError(
                f"No valid samples loaded from: {self.annotation_path}"
            )

    def _load_samples(self) -> list[QASample]:
        samples: list[QASample] = []

        with self.annotation_path.open("r", encoding="utf-8") as f:
            for line_idx, line in enumerate(f, start=1):
                line = line.strip()

                if not line:
                    continue

                try:
                    row = json.loads(line)
                except json.JSONDecodeError as exc:
                    raise ValueError(
                        f"Invalid JSON at line {line_idx} in {self.annotation_path}"
                    ) from exc

                sample = self._row_to_sample(row, line_idx=line_idx)

                if self.require_video_exists and not sample.video_path.exists():
                    raise FileNotFoundError(
                        f"Video file does not exist for sample {sample.sample_id}: "
                        f"{sample.video_path}"
                    )

                sample.validate(require_answer=self.require_answer)
                samples.append(sample)

        return samples

    def _row_to_sample(
        self,
        row: dict[str, Any],
        *,
        line_idx: int,
    ) -> QASample:
        sample_id = str(row.get("sample_id", f"line_{line_idx}"))

        raw_video_path = row.get("video_path")

        if raw_video_path is None:
            raise ValueError(
                f"Missing video_path for sample {sample_id} "
                f"at line {line_idx} in {self.annotation_path}"
            )

        video_path = Path(raw_video_path)

        # If video_path is relative and video_root is given,
        # resolve it under video_root.
        if not video_path.is_absolute() and self.video_root is not None:
            video_path = self.video_root / video_path

        question = row.get("question")

        if question is None:
            raise ValueError(
                f"Missing question for sample {sample_id} "
                f"at line {line_idx} in {self.annotation_path}"
            )

        task_type = row.get("task_type", "multi_choice")

        if task_type not in ["multi_choice", "open_ended"]:
            raise ValueError(
                f"Invalid task_type '{task_type}' for sample {sample_id}. "
                "Expected 'multi_choice' or 'open_ended'."
            )

        options = row.get("options")
        if options is not None:
            options = [str(option) for option in options]

        answer = row.get("answer")
        if answer is not None:
            answer = str(answer)

        duration = row.get("duration")
        if duration is not None:
            duration = float(duration)

        metadata = row.get("metadata", {})
        if metadata is None:
            metadata = {}

        metadata = dict(metadata)
        metadata.setdefault("dataset", "videomme")

        return QASample(
            sample_id=sample_id,
            video_path=video_path,
            question=str(question),
            task_type=task_type,
            options=options,
            answer=answer,
            duration=duration,
            metadata=metadata,
        )

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> QASample:
        return self.samples[idx]

    def __iter__(self) -> Iterator[QASample]:
        return iter(self.samples)